name: SuperMinecraftMaker
main: com.minecade.minecraftmaker.plugin.MinecraftMakerPlugin
version: '${project.version}'
authors: [felipepcjr, SethBling, DonZitrO]
load: startup
commands:
  makerlobby:
    description: Used by spectators to return to maker lobby
    usage: 'Usage: /makerlobby'
    permission-message: 'ยง4You are not allowed to use this command!'
  level:
    description: Used by players to manipulate levels
    usage: 'Usage: /level <action> <params>'
    permission-message: 'ยง4You are not allowed to use this command!'
  maker:
    description: Used by players to interact with other players
    usage: 'Usage: /maker <action> <params>'
    permission-message: 'ยง4You are not allowed to use this command!'
  report:
    description: Used by players to report issues
    usage: 'Usage: /report <report>'
    permission-message: 'ยง4You are not allowed to use this command!'
