name: SuperMinecraftMaker
main: com.minecade.minecraftmaker.plugin.MinecraftMakerPlugin
version: '${project.version}'
authors: [SethBling, tux2, DonZitrO]
load: startup
commands:
  level:
    description: Used by players to manipulate levels
    usage: 'Usage: /level <action> <params>'
    permission-message: 'ยง4You are not allowed to use this command!'
  report:
    description: Used by players to report issues
    usage: 'Usage: /report <report>'
    permission-message: 'ยง4You are not allowed to use this command!'
