package com.minecade.minecraftmaker.level;

public enum LevelStatus {
	CLIPBOARD_COPIED,
	CLIPBOARD_COPY_READY,
	CLIPBOARD_PASTE_READY,
	CLIPBOARD_PASTED,
	COPYING_CLIPBOARD,
	DISABLED,
	EDIT_READY,
	EDITED,
	EDITING,
	LOADING,
	PASTING_CLIPBOARD,
	PLAY_READY,
	PLAYING,
	SAVE_ERROR,
	SAVE_READY,
	SAVED,
	SAVING,
	UNLOAD_READY,
	CLEARED;
}
