package com.minecade.minecraftmaker.level;

public enum LevelStatus {
	CLEARED,
	CLIPBOARD_COPIED,
	CLIPBOARD_COPY_READY,
	CLIPBOARD_ERROR,
	CLIPBOARD_LOADED,
	CLIPBOARD_LOADING,
	CLIPBOARD_PASTE_READY,
	CLIPBOARD_PASTED,
	COPYING_CLIPBOARD,
	DISABLED,
	EDIT_READY,
	EDITED,
	EDITING,
	EDITOR_PLAYING,
	LOADING,
	PASTING_CLIPBOARD,
	PLAY_READY,
	PLAYING,
	PREPARING,
	SAVE_ERROR,
	SAVE_READY,
	SAVED,
	SAVING, 
	UNLOAD_READY;
}
